name: Update Options Sheet

on:
  schedule:
    - cron: "*/55 13-19 * * 1-5"   # every 2 minutes, 9:00–15:59 ET (13–19 UTC, weekdays)
  workflow_dispatch:

jobs:
  run-updater:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run updater
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
          SHEET_URL: ${{ secrets.SHEET_URL }}
          WORKSHEET_NAME: ${{ secrets.WORKSHEET_NAME }}
        run: python updater.py
